project:
  type: website
  output-dir: docs

website:
  #title: "Rishabh Mondal"
  navbar:
   background: primary
   left:
     - href: index.qmd
     - about.qmd
     - href: Conference.qmd 
     - href: workshop.qmd
     - href: blog.qmd # my new navbar page
     - href: gallery.qmd

format:
  html:
    theme: 
      light: minty
      dark: slate
    css: styles.css
editor: visual

